version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      BG_COLOR: teal
