apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: chinaliev_application
          image: application
          ports:
            - containerPort: 5000
          
        - name: mongo:latest
          image: mongo
          ports:
            - containerPort: 27017